name: Deploy React App to ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-2
  ECR_REPOSITORY: ecs-threat-composer-tool
  ACCOUNT_ID:  ${{ secrets.AWS_ACCOUNT_ID }}

jobs:
  deploy:
    name: Build and Push to Amazon ECR
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image (React App with Nginx)
        run: |
          docker build -t $ECR_REPOSITORY:latest .

      - name: Tag image with full ECR URL
        run: |
          docker tag $ECR_REPOSITORY:latest $ACCOUNT_ID.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPOSITORY:latest

      - name: Push image to Amazon ECR
        run: |
          docker push $ACCOUNT_ID.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPOSITORY:latest
