name: Terraform Plan Pipeline

on:
  pull_request:
    types: [opened]
    branches:
      - prod
    paths:
      - "terraform/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: ./terraform

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init

      - name: Terraform fmt
        run: terraform fmt -check

      - name: Terraform validate
        run: terraform validate

      - name: Run tflint
        uses: terraform-linters/setup-tflint@v4
      - run: tflint --init && tflint

      - name: Run Checkov Security Scan
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          check: CKV_AWS_1, CKV_AWS_2, CKV_AWS_3

      - name: Terraform Plan
        run: |
          terraform init
          terraform plan